---
name: Question/Support
description: Ask a question or request support
title: "[QUESTION] "
labels: ["question", "help wanted"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Need help? Have a question? We're here to help! Please fill out the form below.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: "What's your question?"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about what you're trying to do.
      placeholder: "What are you trying to accomplish?"
    validations:
      required: true

  - type: textarea
    id: attempts
    attributes:
      label: What have you tried?
      description: What have you already tried to solve this?
      placeholder: "Describe what you've attempted so far..."

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using?
      placeholder: "e.g., v1.0.0"

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Windows
        - macOS
        - Linux
        - Docker
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any additional information that might be helpful.
